databases:
  - name: time-tracker-db
    plan: free
    databaseName: time_tracker
    user: postgres
services:
  - type: web
    name: time-tracker-backend
    env: docker
    dockerfilePath: backend/Dockerfile
    dockerContext: backend
    plan: free
    autoDeploy: true
    envVars:
      - key: DB_HOST
        fromDatabase:
          name: time-tracker-db
          property: host
      - key: DB_NAME
        fromDatabase:
          name: time-tracker-db
          property: database
      - key: DB_USER
        fromDatabase:
          name: time-tracker-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: time-tracker-db
          property: password
      - key: TOKEN_SECRET
        generateValue: true
  - type: web
    name: time-tracker-frontend
    env: docker
    dockerfilePath: frontend/time-tracker/Dockerfile
    dockerContext: frontend/time-tracker
    plan: free
    autoDeploy: true
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: https://time-tracker-backend.onrender.com